mysql:
  image: mysql:5.7
  container_name: mysql
  volumes:
    - ./database/mysql-data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: "nenis"
  ports:
    - "3306:3306"